name: Generar y Comprimir OpenAPI

on:
  push:
    branches:
      - ejercicio3

jobs:
  generar-codigo:
    runs-on: ubuntu-latest 

    steps:
      - name: Descargar código en runner
        uses: actions/checkout@v4

      - name: Configurar Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Ejecutar comando
        run: java -jar openapi-generator-cli.jar generate -i api.yaml -g python-flask -o ./openapi_server

      - name: Ejecutar comando 2
        run: zip -r openapi_server.zip openapi_server

      - name: Subir artefacto
        uses: actions/upload-artifact@v4
        with:
          name: openapi_server.zip
          path: openapi_server.zip
