name: Generar y Comprimir OpenAPI

on:
  push:
    branches:
      - ejercicio3

jobs:
  generar-codigo:
    runs-on: ubuntu-latest  

    steps:
      - name: Descargar código en runner
        uses: actions/checkout@v4

      - name: Configurar Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Descargar OpenAPI Generator CLI
        run: curl -L https://github.com/OpenAPITools/openapi-generator/releases/download/v5.4.0/openapi-generator-cli.jar -o openapi-generator-cli.jar

      - name: Ejecutar comando
        run: java -jar openapi-generator-cli.jar generate -i api.yaml -g pythonflask -o ./openapi_server

      - name: Comprimir el directorio generado
        run: zip -r openapi_server.zip openapi_server

      - name: Subir artefacto
        uses: actions/upload-artifact@v4
        with:
          name: openapi_server.zip
          path: openapi_server.zip
